# Generated by Django 5.2.8 on 2025-11-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(help_text='Enter the full phone number in international format, e.g., +919876543210', max_length=20, unique=True),
        ),
    ]
