# Generated by Django 5.2.8 on 2025-12-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_type',
            field=models.CharField(blank=True, help_text='MIME type of the media file', max_length=100, null=True),
        ),
    ]
