# Generated by Django 4.2.6 on 2025-12-22 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0005_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, help_text="Agent assigned to handle this customer's chats", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to='whatsapp.agent'),
        ),
    ]
