# Generated by Django 5.2.8 on 2026-02-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0006_customer_assigned_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Block this customer from receiving messages'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_message_from_customer',
            field=models.DateTimeField(blank=True, help_text='Last time customer sent a message (for 12hr window)', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='opt_in_date',
            field=models.DateTimeField(blank=True, help_text='When customer opted in', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='opt_in_method',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp Message'), ('website', 'Website Form'), ('sms', 'SMS'), ('manual', 'Manual Entry'), ('api', 'API')], help_text='How the customer opted in', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='opt_out_date',
            field=models.DateTimeField(blank=True, help_text='When customer opted out', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='opted_in',
            field=models.BooleanField(default=False, help_text='Customer has given consent to receive messages'),
        ),
        migrations.AddField(
            model_name='customer',
            name='opted_out',
            field=models.BooleanField(default=False, help_text='Customer has unsubscribed'),
        ),
        migrations.AddField(
            model_name='message',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='When message was delivered', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='error_code',
            field=models.CharField(blank=True, help_text='WhatsApp API error code', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='error_message',
            field=models.TextField(blank=True, help_text='WhatsApp API error message', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='failed_at',
            field=models.DateTimeField(blank=True, help_text='When message failed', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='When message was read by recipient', null=True),
        ),
    ]
